// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenMdFile() {
  return window['go']['main']['App']['OpenMdFile']();
}

export function SaveMdFile(arg1) {
  return window['go']['main']['App']['SaveMdFile'](arg1);
}
